const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const state={view:'customers',customers:[],knowledge:[]};
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const date=(v)=>v?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v)):'未启用';
let toastTimer;function toast(m){$('#adminToast').textContent=m;$('#adminToast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#adminToast').classList.remove('show'),2500)}
function login(m=''){ $('#adminShell').hidden=true;$('#loginScreen').hidden=false;$('#loginMessage').textContent=m;$('#username').focus() }function workspace(){ $('#loginScreen').hidden=true;$('#adminShell').hidden=false }
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options,headers:{'content-type':'application/json',...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(r.status===401){login('会话已失效，请重新登录');throw new Error('unauthorized')}if(!r.ok)throw new Error(b.message||'请求失败');return b}
const member=(c)=>!c.membershipExpiresAt?'未启用':new Date(c.membershipExpiresAt)<new Date()?'已到期':'会员有效';
async function handleLogin(e){e.preventDefault();try{await api('/api/sales/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});$('#password').value='';const session=await api('/api/session');$('#advisorName').textContent=session.principal.displayName;workspace();await loadCustomers()}catch(err){$('#loginMessage').textContent=err.message}}
async function logout(){await api('/api/session/logout',{method:'POST',body:'{}'}).catch(()=>{});login('已安全退出')}
function setView(view){state.view=view;$('#customersView').hidden=view!=='customers';$('#knowledgeView').hidden=view!=='knowledge';$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#pageEyebrow').textContent=view==='customers'?'CUSTOMER CONTINUITY':'SALES PLAYBOOK';$('#pageTitle').textContent=view==='customers'?'客户管理':'销售答疑';view==='customers'?loadCustomers():loadKnowledge()}
async function loadCustomers(){const q=$('#customerSearch').value.trim();const data=await api(`/api/sales/customers?query=${encodeURIComponent(q)}&pageSize=100`);state.customers=data.items;$('#customerCount').textContent=`${data.total} 位客户`;$('#customersBody').innerHTML=data.items.map(c=>`<tr data-customer="${esc(c.id)}"><td><strong>${esc(c.name)}</strong><small>${esc(c.id)}</small></td><td>${esc(c.contact||c.email||'—')}</td><td>${esc(c.periodLabel||'—')}</td><td>${date(c.membershipExpiresAt)}</td><td><span class="status-pill">${member(c)}</span></td></tr>`).join('');$('#lastUpdated').textContent=`更新于 ${new Date().toLocaleTimeString('zh-CN',{hour12:false})}`}
function close(){ $('#drawer').hidden=true;document.body.style.overflow='' }
async function openCustomer(id){const c=await api(`/api/sales/customers/${encodeURIComponent(id)}`);const active=member(c)==='会员有效';$('#drawerTitle').textContent=c.name;$('#drawerContent').innerHTML=`<div class="drawer-content"><section class="order-identity"><p>${esc(c.id)}</p><h3>${esc(c.name)}</h3><span class="status-pill">${member(c)}</span></section><dl class="detail-grid"><div><dt>联系方式</dt><dd>${esc(c.contact||c.email||'—')}</dd></div><div><dt>会员到期</dt><dd>${date(c.membershipExpiresAt)}</dd></div><div><dt>健康资料准备</dt><dd>${esc(c.medicalDocumentsStatus||'待跟进')}</dd></div><div><dt>内部预约</dt><dd>${(c.internalBookings||[]).length} 条</dd></div></dl>${active?`<form class="admin-form" id="bookingForm"><h4>建立会员后续预约</h4><label>期次编号<input id="periodId" placeholder="例如 20270101" required></label><label>期次名称<input id="periodLabel" placeholder="例如 2027·一月首期" required></label><label>同行人数<input id="guestCount" type="number" min="1" max="10" value="1" required></label><label>同行关系<input id="relationship" placeholder="本人 / 父母 / 家庭"></label><label>内部备注<textarea id="bookingNote"></textarea></label><button type="submit">建立内部预约</button></form>`:'<section class="detail-section"><h4>预约状态</h4><p>会员未启用或已到期，应按新客户流程重新评估；销售无权调整会员期限。</p></section>'}</div>`;$('#drawer').hidden=false;document.body.style.overflow='hidden';if($('#bookingForm'))$('#bookingForm').onsubmit=async e=>{e.preventDefault();await api(`/api/sales/customers/${encodeURIComponent(id)}/internal-bookings`,{method:'POST',body:JSON.stringify({periodId:$('#periodId').value,periodLabel:$('#periodLabel').value,guestCount:Number($('#guestCount').value),relationship:$('#relationship').value,note:$('#bookingNote').value})});toast('后续预约已建立');close();await loadCustomers()}}
async function loadKnowledge(){const data=await api('/api/sales/knowledge');state.knowledge=data.items;renderKnowledge()}
function renderKnowledge(){const q=$('#knowledgeSearch').value.trim().toLowerCase();const items=state.knowledge.filter(i=>`${i.stage}${i.question}${i.shortAnswer}${i.talkingPoints.join('')}`.toLowerCase().includes(q));$('#knowledgeList').innerHTML=items.map(i=>`<article class="knowledge-card"><header><span>${esc(i.stage)}</span><b>标准口径</b></header><h3>${esc(i.question)}</h3><p>${esc(i.shortAnswer)}</p><ul>${i.talkingPoints.map(p=>`<li>${esc(p)}</li>`).join('')}</ul>${i.sources.length?`<small>参考：${i.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noreferrer">${esc(s.title)}</a>`).join(' · ')}</small>`:''}</article>`).join('')}
$('#loginForm').onsubmit=handleLogin;$('#logoutButton').onclick=logout;$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#refreshCurrent').onclick=()=>state.view==='customers'?loadCustomers():loadKnowledge();$('#customerSearch').oninput=()=>setTimeout(loadCustomers,180);$('#knowledgeSearch').oninput=renderKnowledge;$('#customersBody').onclick=e=>{const row=e.target.closest('[data-customer]');if(row)openCustomer(row.dataset.customer)};$$('[data-close-drawer]').forEach(b=>b.onclick=close);
try{const session=await api('/api/session');if(session.principal.role!=='sales')throw new Error('unauthorized');$('#advisorName').textContent=session.principal.displayName;workspace();await loadCustomers()}catch(err){if(err.message!=='unauthorized')login('工作台连接失败')}
