import { sessionLoginMessage } from './session-state.mjs';

const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const state={view:'stats',customers:[],staff:[],knowledge:[],config:null,chart:null,trafficPeriod:'day',trafficClassification:'all',trafficPage:1};
const titles={stats:['VISITOR INTELLIGENCE','访问统计'],customers:['CUSTOMER CONTINUITY','客户管理'],knowledge:['SALES PLAYBOOK','销售答疑'],config:['COMMERCIAL CONTROL','商业配置'],staff:['ACCESS CONTROL','团队权限']};
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=(v)=>`¥ ${Number(v||0).toLocaleString('zh-CN')}`;
const date=(v)=>v?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v)):'未启用';
let toastTimer,sessionEstablished=false;
function toast(message){$('#adminToast').textContent=message;$('#adminToast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#adminToast').classList.remove('show'),2600)}
function login(message=''){ $('#adminShell').hidden=true;$('#loginScreen').hidden=false;$('#loginMessage').textContent=message;$('#password').focus() }
function workspace(){ $('#loginScreen').hidden=true;$('#adminShell').hidden=false }
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options,headers:{'content-type':'application/json',...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(r.status===401){login(sessionLoginMessage(sessionEstablished));throw new Error(b.message||'unauthorized')}if(!r.ok)throw new Error(b.message||'请求失败');return b}
function stamp(){ $('#lastUpdated').textContent=`更新于 ${new Date().toLocaleTimeString('zh-CN',{hour12:false})}` }

async function handleLogin(e){e.preventDefault();const btn=$('#loginButton');btn.disabled=true;try{await api('/api/owner/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';sessionEstablished=true;workspace();await loadCurrent()}catch(err){$('#loginMessage').textContent=err.message==='unauthorized'?'':err.message}finally{btn.disabled=false}}
async function logout(){await api('/api/session/logout',{method:'POST',body:'{}'}).catch(()=>{});sessionEstablished=false;login('已安全退出')}
function setView(view){state.view=view;$$('.view-panel').forEach(p=>p.hidden=p.id!==`${view}View`);$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));[$('#pageEyebrow').textContent,$('#pageTitle').textContent]=titles[view];loadCurrent()}
async function loadCurrent(){const loaders={stats:loadStats,customers:loadCustomers,knowledge:loadKnowledge,config:loadConfig,staff:loadStaff};await loaders[state.view]();stamp()}

const trafficDate=(value)=>value?new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)):'—';
function renderTrafficIps(stats){const items=stats.topIPs||[];const pagination=stats.pagination||{};$('#trafficIpsBody').innerHTML=items.length?items.map(item=>`<tr><td><strong>${esc(item.ip)}</strong></td><td>${esc(item.location||'地区待确认')}</td><td>${Number(item.count||0).toLocaleString('zh-CN')}<small>恶意路径 ${Number(item.maliciousCount||0)}</small></td><td>${trafficDate(item.lastVisit)}</td><td><span class="traffic-status traffic-${esc(item.classification?.kind||'unknown')}">${esc(item.classification?.label||'信息不足')}</span></td><td>${esc(item.classification?.reason||'尚无足够访问序列')}</td></tr>`).join(''):'<tr><td class="empty-state" colspan="6">当前筛选下暂无 IP 记录</td></tr>';$('#trafficPageInfo').textContent=`${pagination.currentPage||0} / ${pagination.totalPages||0} 页 · ${pagination.totalIPs||0} 个 IP`;$('#trafficPrev').disabled=!pagination.hasPrevPage;$('#trafficNext').disabled=!pagination.hasNextPage}
async function loadStats(){const query=new URLSearchParams({period:state.trafficPeriod,classification:state.trafficClassification,page:String(state.trafficPage)});const [live,stats]=await Promise.all([api('/api/owner/realtime'),api(`/api/owner/stats?${query}`)]);$('#todayVisits').textContent=live.todayVisits||0;$('#todayUnique').textContent=live.todayUniqueIPs||0;$('#totalVisits').textContent=live.totalVisits||0;$('#totalIPs').textContent=live.totalIPs||0;const summary=stats.summary||{};$('#trafficLikelyHuman').textContent=summary.likely_human||0;$('#trafficAutomated').textContent=summary.automated||0;$('#trafficScan').textContent=summary.scan||0;$('#trafficHighRisk').textContent=summary.high_risk||0;$('#trafficPeriod').value=state.trafficPeriod;$('#trafficClassification').value=state.trafficClassification;if(state.chart)state.chart.destroy();state.chart=new Chart($('#visitsChart'),{type:'line',data:{labels:(stats.periodData||[]).map(x=>x.label||x.date),datasets:[{label:'访问次数',data:(stats.periodData||[]).map(x=>x.visits),borderColor:'#b9a27b',backgroundColor:'rgba(185,162,123,.09)',fill:true,tension:.32,pointRadius:1},{label:'独立 IP',data:(stats.periodData||[]).map(x=>x.uniqueIPs),borderColor:'#789d88',backgroundColor:'transparent',fill:false,tension:.32,pointRadius:1}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#777b76'}}},scales:{x:{ticks:{color:'#666'},grid:{color:'rgba(221,207,179,.06)'}},y:{ticks:{color:'#666'},grid:{color:'rgba(221,207,179,.06)'}}}}});renderTrafficIps(stats)}
function memberLabel(c){if(!c.membershipExpiresAt)return '未启用';const days=Math.ceil((new Date(c.membershipExpiresAt)-Date.now())/86400000);if(days<0)return '已到期';if(days<=60)return `${days} 天后到期`;return '有效会员'}
function salesName(id){return state.staff.find(s=>s.id===id)?.displayName||'待分配'}
async function ensureStaff(){if(!state.staff.length)state.staff=(await api('/api/owner/staff')).items}
async function loadCustomers(){await ensureStaff();const q=$('#customerSearch').value.trim();const data=await api(`/api/owner/customers?query=${encodeURIComponent(q)}&pageSize=100`);state.customers=data.items;$('#customerCount').textContent=`${data.total} 位客户`;$('#navNewCount').textContent=data.summary?.new||0;$('#customersBody').innerHTML=data.items.map(c=>`<tr data-customer="${esc(c.id)}" tabindex="0"><td><strong>${esc(c.name)}</strong><small>${esc(c.id)}</small></td><td>${esc(c.contact||c.email||'—')}</td><td>${esc(c.periodLabel||'—')}</td><td>${date(c.membershipExpiresAt)}</td><td>${esc(salesName(c.assignedSalesId))}</td><td><span class="status-pill">${esc(memberLabel(c))}</span></td></tr>`).join('')}
function openDrawer(title,html,eyebrow='PRIVATE RECORD'){ $('#drawerTitle').textContent=title;$('#drawerEyebrow').textContent=eyebrow;$('#drawerContent').innerHTML=`<div class="drawer-content">${html}</div>`;$('#drawer').hidden=false;document.body.style.overflow='hidden' }
function closeDrawer(){ $('#drawer').hidden=true;document.body.style.overflow='' }
async function openCustomer(id){await ensureStaff();const c=await api(`/api/owner/customers/${encodeURIComponent(id)}`);const files=(c.attachments||[]).map(f=>`<a href="/api/owner/applications/${encodeURIComponent(c.id)}/attachments/${encodeURIComponent(f.id)}">${esc(f.displayName)} · 下载</a>`).join('')||'无附件';openDrawer(c.name,`<section class="order-identity"><p>${esc(c.id)}</p><h3>${esc(c.name)}</h3><span class="status-pill">${esc(memberLabel(c))}</span></section><dl class="detail-grid"><div><dt>联系方式</dt><dd>${esc(c.contact||c.email||'—')}</dd></div><div><dt>申请期次</dt><dd>${esc(c.periodLabel||'—')}</dd></div><div><dt>会员到期</dt><dd>${date(c.membershipExpiresAt)}</dd></div><div><dt>资料附件</dt><dd class="download-list">${files}</dd></div></dl><form class="admin-form" id="customerAdminForm"><label>负责销售<select id="assignSales"><option value="">待分配</option>${state.staff.map(s=>`<option value="${esc(s.id)}" ${s.id===c.assignedSalesId?'selected':''}>${esc(s.displayName)}</option>`).join('')}</select></label><button type="button" id="saveAssignment">保存客户归属</button><label>赠送 / 调整会员期限<input id="memberExpiry" type="date" value="${c.membershipExpiresAt?c.membershipExpiresAt.slice(0,10):''}"></label><label>调整原因<textarea id="memberReason" placeholder="必填：赠送原因或调整依据"></textarea></label><button type="button" id="adjustMembership">仅所有者可调整</button>${!c.membershipExpiresAt?'<button type="button" class="secondary-action" id="activateMembership">确认首次方案并启用会员</button>':''}</form>`);$('#saveAssignment').onclick=async()=>{await api(`/api/owner/customers/${encodeURIComponent(id)}/assignment`,{method:'PATCH',body:JSON.stringify({salesId:$('#assignSales').value})});toast('客户归属已保存');await loadCustomers()};$('#adjustMembership').onclick=async()=>{await api(`/api/owner/customers/${encodeURIComponent(id)}/membership`,{method:'POST',body:JSON.stringify({type:'owner_adjusted',expiresAt:$('#memberExpiry').value,reason:$('#memberReason').value})});toast('会员期限已调整并记录原因');closeDrawer();await loadCustomers()};if($('#activateMembership'))$('#activateMembership').onclick=async()=>{await api(`/api/owner/customers/${encodeURIComponent(id)}/membership`,{method:'POST',body:JSON.stringify({type:'plan_confirmed'})});toast('首年会员已启用');closeDrawer();await loadCustomers()}}

async function loadKnowledge(){const data=await api('/api/owner/knowledge');state.knowledge=data.items;renderKnowledge()}
function renderKnowledge(){const q=$('#knowledgeSearch').value.trim().toLowerCase();const items=state.knowledge.filter(i=>`${i.stage}${i.question}${i.shortAnswer}`.toLowerCase().includes(q));$('#knowledgeList').innerHTML=items.map(i=>`<article class="knowledge-card" data-knowledge="${i.id}"><header><span>${esc(i.stage)}</span><b>${i.published?'已发布':'草稿'}</b></header><h3>${esc(i.question)}</h3><p>${esc(i.shortAnswer)}</p><small>${i.talkingPoints.map(esc).join(' · ')}</small></article>`).join('')}
function knowledgeForm(item={}){openDrawer(item.id?'编辑答疑':'新增答疑',`<form class="admin-form" id="knowledgeForm"><label>客户旅程阶段<select id="kStage">${['品牌与定位','首次沟通','预约规则','会员机制','健康资料','方案与费用','日本准备','抵日接待','医疗服务','在日行程','回国延续','异议与边界'].map(s=>`<option ${s===item.stage?'selected':''}>${s}</option>`).join('')}</select></label><label>客户问题<input id="kQuestion" value="${esc(item.question||'')}"></label><label>简明回答<textarea id="kAnswer">${esc(item.shortAnswer||'')}</textarea></label><label>销售要点（每行一条）<textarea id="kPoints">${esc((item.talkingPoints||[]).join('\n'))}</textarea></label><label>排序<input id="kOrder" type="number" value="${item.order||999}"></label><label class="check-field"><input id="kPublished" type="checkbox" ${item.published===false?'':'checked'}> 对销售发布</label><button type="submit">保存答疑</button></form>`);$('#knowledgeForm').onsubmit=async e=>{e.preventDefault();const body={stage:$('#kStage').value,question:$('#kQuestion').value,shortAnswer:$('#kAnswer').value,talkingPoints:$('#kPoints').value.split('\n').filter(Boolean),sources:item.sources||[],published:$('#kPublished').checked,order:Number($('#kOrder').value)};await api(item.id?`/api/owner/knowledge/${item.id}`:'/api/owner/knowledge',{method:item.id?'PATCH':'POST',body:JSON.stringify(body)});closeDrawer();toast('答疑已保存');await loadKnowledge()}}

const numericConfigLabels={fullPlanPrice:'标准方案价格',membershipFee:'会员年费',membershipMonths:'会员期限（月）',standardCapacity:'标准期内部席位',filialPrice:'敬亲礼遇期价格',filialFamilyGroups:'公开家庭组数',filialMaxGuests:'内部人数上限'};
function renderPrivateJournalControl(){const enabled=state.config?.showPrivateJournal===true;$('#privateJournalStatus').textContent=enabled?'已公开':'未公开';const button=$('#privateJournalToggle');button.textContent=enabled?'停止公开':'立即公开';button.disabled=false}
async function loadConfig(){state.config=await api('/api/owner/config');const numericFields=Object.entries(numericConfigLabels).map(([key,label])=>`<label><span>${label}</span><input name="${key}" type="number" value="${state.config[key]}"><small>${key.includes('Price')||key==='membershipFee'?money(state.config[key]):'仅内部可见'}</small></label>`).join('');$('#configFields').innerHTML=numericFields;renderPrivateJournalControl()}
async function togglePrivateJournal(){const button=$('#privateJournalToggle');const enabled=state.config?.showPrivateJournal===true;button.disabled=true;try{const saved=await api('/api/owner/config/private-journal',{method:'PATCH',body:JSON.stringify({enabled:!enabled})});state.config={...state.config,showPrivateJournal:saved.showPrivateJournal};renderPrivateJournalControl();toast(saved.showPrivateJournal?'方舟生命纪行已公开':'方舟生命纪行已停止公开')}catch(error){toast(error.message)}finally{button.disabled=false}}
async function saveConfig(e){e.preventDefault();const body={reason:$('#configReason').value};new FormData(e.currentTarget).forEach((v,k)=>{if(k in numericConfigLabels)body[k]=Number(v)});await api('/api/owner/config',{method:'PATCH',body:JSON.stringify(body)});$('#configReason').value='';toast('商业配置已保存');await loadConfig()}

async function loadStaff(){state.staff=(await api('/api/owner/staff')).items;$('#staffList').innerHTML=state.staff.map(s=>`<article class="staff-card"><div><span>${s.active?'ACTIVE':'DISABLED'}</span><h3>${esc(s.displayName)}</h3><p>${esc(s.username)}</p></div><div><button data-staff-status="${s.id}" data-active="${!s.active}">${s.active?'停用':'启用'}</button><button data-staff-reset="${s.id}">重置密码</button></div></article>`).join('')}
function newStaff(){openDrawer('新增销售账号',`<form class="admin-form" id="staffForm" autocomplete="off"><label>销售姓名<input id="sName" autocomplete="name" required></label><label>登录用户名<input id="sUsername" autocomplete="off" required></label><label>初始密码<input id="sPassword" type="password" autocomplete="new-password" minlength="10" required></label><button type="submit">创建账号</button></form>`);$('#staffForm').onsubmit=async e=>{e.preventDefault();await api('/api/owner/staff',{method:'POST',body:JSON.stringify({displayName:$('#sName').value,username:$('#sUsername').value,password:$('#sPassword').value})});closeDrawer();toast('销售账号已创建');await loadStaff()}}

$('#loginForm').onsubmit=handleLogin;$('#logoutButton').onclick=logout;$('#refreshCurrent').onclick=loadCurrent;$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#customerSearch').oninput=()=>setTimeout(loadCustomers,180);$('#customersBody').onclick=e=>{const r=e.target.closest('[data-customer]');if(r)openCustomer(r.dataset.customer)};$('#knowledgeSearch').oninput=renderKnowledge;$('#knowledgeList').onclick=e=>{const c=e.target.closest('[data-knowledge]');if(c)knowledgeForm(state.knowledge.find(i=>i.id===c.dataset.knowledge))};$('#newKnowledge').onclick=()=>knowledgeForm();$('#configForm').onsubmit=saveConfig;$('#privateJournalToggle').onclick=togglePrivateJournal;$('#trafficPeriod').onchange=e=>{state.trafficPeriod=e.target.value;state.trafficPage=1;loadStats()};$('#trafficClassification').onchange=e=>{state.trafficClassification=e.target.value;state.trafficPage=1;loadStats()};$('#trafficPrev').onclick=()=>{if(state.trafficPage>1){state.trafficPage-=1;loadStats()}};$('#trafficNext').onclick=()=>{state.trafficPage+=1;loadStats()};$('#newStaff').onclick=newStaff;$('#staffList').onclick=async e=>{const status=e.target.closest('[data-staff-status]');const reset=e.target.closest('[data-staff-reset]');if(status){await api(`/api/owner/staff/${status.dataset.staffStatus}/status`,{method:'PATCH',body:JSON.stringify({active:status.dataset.active==='true'})});toast('账号状态已更新');await loadStaff()}if(reset){const password=prompt('输入新的临时密码（至少 10 位）');if(password){await api(`/api/owner/staff/${reset.dataset.staffReset}/reset-password`,{method:'POST',body:JSON.stringify({password})});toast('密码已重置，旧会话已失效')}}};$$('[data-close-drawer]').forEach(b=>b.onclick=closeDrawer);
try{const session=await api('/api/session');if(session.principal.role!=='owner')throw new Error('unauthorized');sessionEstablished=true;workspace();await loadCurrent()}catch(err){if(err.message!=='unauthorized')login('后台连接失败')}
